import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Jersey_10 } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./theme-provider";
import Navbar from "@/components/landing-page/Navbar";
// import Footer from "@/components/landing-page/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const GameFont = Jersey_10({
  subsets: ["latin"],
  variable: "--font-game",
  weight: "400"
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" suppressHydrationWarning 
      className={`${geistSans.variable} ${geistMono.variable} ${GameFont.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
                  {/* Header */}
      <Navbar />
        {children}

              {/*  Footer */}
      {/* <Footer /> */}
        </ThemeProvider>

        </body>
    </html>
  );
}
